version: '3'
services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - '.:/usr/src/app'
    ports:
      - '80:3000'
    depends_on:
      - db
    environment:
      DB_NAME: test_db
      DB_USER: root
      DB_PASS: ABC12abc
      DB_HOST: db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ABC12abc
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: ABC12abc
    ports:
      - 3307:3306
